language: node_js
node_js:
  - "5"
env:
  NODE_ENV=test
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/33b929f670a3cfa6718e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
